#! /usr/bin/env python
# -*- coding: utf-8 -*-

# @autor: Diego Caraballo
# @date: 08/05/13
# @version: python 2.7.4
# Grupo Estudio Python

#Hacer un método que recibe un numero positivo, y devuelve la suma de cada digito.

ingreso = input("Dame un numero entero con mas de una cifra: ")

def suma_de_digitos(n):
    a = 0
    n = str(n)
    for i in n:
      a = a + int(i)
    return a

resultado = suma_de_digitos(ingreso)

print "La suma fue:", resultado


